### ISSUE TITLE
Unable to get it working with nvim-surround

### ISSUE THREAD

**Issue by gvolpe** [XXiaoA/ns-textobject.nvim#11]
Hi,

The plugin looks really cool, great work! I would like to give it a try, but I haven't been able to get it working. Is this the right setup?

```lua
require('nvim-surround').setup()
require('ns-textobject').setup()
```

The plugin seems to load, but trying the example from the README `ysiwl` only adds an `l` around the word, as if I was only using `nvim-surround`. Is this keymap something I need to manually configure?

Thanks.

**Comment by XXiaoA** [comment]
Oh, thanks. I forgot to add some explanations below the demo.  You have to add some configurations to achieve that.

Will add them soon.

**Comment by gvolpe** [comment]
Thanks for the quick reply! I guess something like this is needed?

```lua
require("ns-textobject").map_textobj("l", "links")
```

**Comment by XXiaoA** [comment]
No, map_textobj is used to create textobject which has been configured in nvim-surround manually. Check the readme under demo.

**Comment by gvolpe** [comment]
Thanks for documenting it! Unfortunately, still doesn't work for me. Am I missing something else?

```lua
require('nvim-surround').setup()

require('ns-textobject').setup()

require('nvim-surround').buffer_setup({
  surrounds = {
    ["l"] = {
      add = function()
        local clipboard = vim.fn.getreg("+"):gsub("\n", "")
        return {
          { "[" },
          { "](" .. clipboard .. ")" },
        }
      end,
      find = "%b[]%b()",
      delete = "^(%[)().-(%]%b())()$",
      change = {
        target = "^()()%b[]%((.-)()%)$",
        replacement = function()
          local clipboard = vim.fn.getreg("+"):gsub("\n", "")
          return {
            { "" },
            { clipboard },
          }
        end,
      },
    },
  }
})
```

**Comment by XXiaoA** [comment]
Ummm, maybe you should check the nvim-surround's doc carefully. There are two chioce now:
+ remove all `buffer_setup` function into `~/.config/nvim/after/ftplugin/markdown.lua` and then this feature will only work in markdown file.
+ remove the first `surround.setup` and then rename `buffer_setup` to `setup`. This method will make the link surround work anywhere.

**Comment by gvolpe** [comment]
The second approach did the trick, thanks! I'll investigate the other approach, seems a better way to do this.
